### ISSUE TITLE
Icons Missing in Development v0.10.4

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Installer#128]
I was prompted to update to Super.Human.Installer Development v0.10.4 today (I'm not sure when I last updated).  I found that the icons did not display after the update:

![image](https://github.com/user-attachments/assets/5f7088ba-b669-41c5-9d15-e928849f5a5b)

I am testing on macOS Ventura (13.6.7).

Is this related to [this update](https://github.com/Moonshine-IDE/Super.Human.Installer/commit/c3e7e660aae283887cfa661c362bd38797fe55e5)?  I don't currently remember how the development releases are working - the update chain I checked had not been updated since 2023.

**Comment by piotrzarzycki21** [comment]
@JoelProminic Can't reproduce this on my macOS Sequoia 15.2 (24C101). What is your version of macOS? It should be fixed in #127
@rat-moonshine can you install 0.10.4 and report back if you have such problems ?

**Comment by rat-moonshine** [comment]
I installed on macOS Sequoia (macOS version shouldn't be a matter if application packaging is alright) and I couldn't able to reproduce missing icon problem:
![image](https://github.com/user-attachments/assets/5c6a853c-cd10-471b-b736-f05f443d4235)

On Windows v0.10.4, it is also looks correct.

**Comment by JoelProminic** [comment]
I am testing on macOS Ventura (13.6.7).  For #127, I see there was a delay when loading assets, but in my case, I see the icons are still not loaded when I checked the running application after the weekend.   I don't see any obvious errors in the log.

**Comment by JoelProminic** [comment]
This also makes the settings page unusable:
![image](https://github.com/user-attachments/assets/990bdd51-10b4-4a0e-8873-1223a4de9190)

**Comment by piotrzarzycki21** [comment]
@JoelProminic Can you please go to Applications -> SuperHumanInstallerDev - Show Package Contenst -> Contents -> Resources -> assets -> images - let me know if you are seeing images there.

**Comment by JoelProminic** [comment]
I do see files here.  Notice that most of them are nested under "common":
![image](https://github.com/user-attachments/assets/49a1868b-6d31-4a85-a500-06dae4ea6d05)

**Comment by piotrzarzycki21** [comment]
A silly question, but have you ever build from source code SHI ?

**Comment by JoelProminic** [comment]
Not that I remember, but I can go through the instructions in the README or GitHub Actions if needed.    If you are worried about old files being included in my application install, I can do a fresh install.

**Comment by piotrzarzycki21** [comment]
Well the weird things happened when I have in my build directory SHI compiled, SHI installed. When you are in Spotlight Search what do you see ?

<img width="596" alt="Screenshot 2025-01-07 at 19 35 59" src="https://github.com/user-attachments/assets/4cf76997-cbb4-43c7-9387-2b5f62d5b7f3" />

**Comment by piotrzarzycki21** [comment]
What if you remove complete SHI and install it - did you try that approach ?

**Comment by piotrzarzycki21** [comment]
@JoelProminic Please install following build it is version 0.10.14. Let me know if you are seeing "Play" icon on the main screen, whether it loads without any delay. 

<img width="164" alt="Image" src="https://github.com/user-attachments/assets/ee9194fd-2d08-470a-9dcc-9f63a48d28a0" />

https://github.com/Moonshine-IDE/Super.Human.Installer/actions/runs/12893607814

**Comment by JoelProminic** [comment]
@piotrzarzycki21, I confirmed that the play button (but only the play button) is fixed now:

<img width="497" alt="Image" src="https://github.com/user-attachments/assets/df8a3998-e3da-4569-89c8-fe664248502f" />

![Image](https://github.com/user-attachments/assets/4e5dc927-e789-4828-b59d-dbe572cb29c6)

What was the problem here?   Do we need to watch for similar problems in other applications?

**Comment by piotrzarzycki21** [comment]
I have revert my changes and get back to the way how it was loaded before. I think it was something with OpenFL - I will share my assumption tomorrow. Will try to get stuff working for whole application - expect official upgrade.

**Comment by piotrzarzycki21** [comment]
I'm attaching video, after bring back previous way of loading icons issue returns back: 

https://github.com/user-attachments/assets/90540ced-67a2-4c2a-8c7b-5fc18be26411

**Comment by piotrzarzycki21** [comment]
@JoelProminic please try newest development version 0.10.15 - you should get update prompt.

**Comment by piotrzarzycki21** [comment]
If we see this issue after update all libraries - non of our other applications is using newest OpenFL yet. I have raised that issue on FeathersUI discord - let's see if someone will be able to explain what has happened.

**Comment by piotrzarzycki21** [comment]
@JoelProminic Version is updated 0.10.16, so when you have time please let me know if everything is still working here.
